# Generated by Django 5.0 on 2023-12-05 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('fabricante', models.CharField(blank=True, max_length=200)),
                ('descrição', models.TextField()),
                ('lote', models.CharField(max_length=10)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('preco_de_compra', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
